"""
Serves the docs/ folder (the Outlook add-in: manifest.xml, taskpane.html,
taskpane.js, icons) over HTTPS on https://localhost:3000, using the
certificate generated by generate_cert.py.

Usage:
    python tools/generate_cert.py   # once, then trust the cert (see docs/README.md)
    python tools/serve.py           # keep this running while using the add-in
"""

import http.server
import os
import ssl

PORT = 3000
HERE = os.path.dirname(os.path.abspath(__file__))
DOCS_DIR = os.path.join(HERE, "..", "docs")
CERT_PATH = os.path.join(HERE, "localhost-cert.pem")
KEY_PATH = os.path.join(HERE, "localhost-key.pem")


class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=DOCS_DIR, **kwargs)

    def end_headers(self):
        self.send_header("Access-Control-Allow-Origin", "*")
        super().end_headers()


def main():
    if not (os.path.exists(CERT_PATH) and os.path.exists(KEY_PATH)):
        raise SystemExit(
            "Certificate not found. Run 'python tools/generate_cert.py' first."
        )

    httpd = http.server.HTTPServer(("localhost", PORT), Handler)

    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    context.load_cert_chain(certfile=CERT_PATH, keyfile=KEY_PATH)
    httpd.socket = context.wrap_socket(httpd.socket, server_side=True)

    print(f"Serving {os.path.abspath(DOCS_DIR)}")
    print(f"  Manifest:  https://localhost:{PORT}/manifest.xml")
    print(f"  Taskpane:  https://localhost:{PORT}/taskpane.html")
    print("Keep this window open while using the add-in. Ctrl+C to stop.")
    httpd.serve_forever()


if __name__ == "__main__":
    main()
